### ISSUE TITLE
would you please provide a dome for example? 

### ISSUE THREAD

**Issue by lijasonvip** [wangkirin/helloworld#1] opened 2018-03-20 03:03 UTC
Thank you very much!

**Comment by WillemJiang** [comment] 2018-03-20 03:30
Keep adding comments.

**Comment by WillemJiang** [comment] 2018-03-20 03:32
why are you close this issue.

**Closed as completed** 2018-03-20 03:31 UTC

**Comment by wangkirin** [comment] 2018-03-20 03:54
that means if the issue is closed ,people can also comment?
